TEAMS_MAPPING = {
    "Bills": "BUF",
    "Dolphins": "MIA",
    "Patriots": "NE",
    "Jets": "NYJ",
    "Browns": "CLE",
    "Bengals": "CIN",
    "Ravens": "BAL",
    "Steelers": "PIT",
    "Jaguars": "JAX",
    "Colts": "IND",
    "Texans": "HOU",
    "Titans": "TEN",
    "Chargers": "LAC",
    "Chiefs": "KC",
    "Raiders": "LV",
    "Broncos": "DEN",
    "Giants": "NYG",
    "Eagles": "PHI",
    "Football Team": "WSH",
    "Cowboys": "DAL",
    "Packers": "GB",
    "Vikings": "MIN",
    "Bears": "CHI",
    "Lions": "DET",
    "Panthers": "CAR",
    "Saints": "NO",
    "Falcons": "ATL",
    "Buccaneers": "TB",
    "Seahawks": "SEA",
    "49ers": "SF",
    "Cardinals": "ARI",
    "Rams": "LAR",
}
